### ISSUE TITLE
Hierarchic labels

### ISSUE THREAD

**Issue by nmb** [pekrau/Publications#181]
It would be nice to be able to view all publications from a platform, either by being able to select multiple labels (facilities), or - better - by introducing platforms as (meta) labels.
Arnold: We would like to be able to assign categories and potentially subcategories according to types of data available from each publication. I see that there is a possibility to add "labels" now, so only one level of categories (no subcategories). I can in principle just use labels for what we need. We can, for example, name categories as "Other data types > Serology data" to denote a subcategory. So for me now it's fine. But a nicer solution would, of course, be to have subcategories as the feature. So if it's possible, that's great, but if not, no worries.

**Comment by pekrau** [comment]
I will not add metalabels; too much complexity for insufficient benefit.
However, being able to see list of union or intersection of labels is more useful. Will consider it.

**Comment by pekrau** [comment]
Meta-labels, or groups. Also consider temporal label issue.

**Comment by pekrau** [comment]
- Add key "superlabel" in label.
- If none in a label, then it is a superlabel, and is shown.
- If it is defined, it is a pointer (docid) to another label (which must be a superlabel).
- If it is defined, then that label is a sublabel.

**Comment by pekrau** [comment]
Restart this issue.
