### ISSUE TITLE
Feature request: show "Added by" in edit view.

### ISSUE THREAD

**Issue by nmb** [pekrau/Publications#183]
It would be great to be able to see who added an entry to the database, and when they did it. As this information is not of general interest, it should only be shown in the edit view.

**Comment by pekrau** [comment]
Not sure I understand. Does not the log page show the info you want? See e.g. https://publications.scilifelab.se/logs/ecc7551bf07d4ecf930ff13d013aeee3

**Comment by nmb** [comment]
Sorry - my bad, did not see the log button before!
