### ISSUE TITLE
Option to specify DOI when adding publications manually

### ISSUE THREAD

**Issue by akochari** [pekrau/Publications#293]
This is overall not a big issue, but just a minor improvement suggestion.
The manual publication addition form does not currently allow to add a DOI because the use of this form is discouraged when DOI is known. However, since crossref is not working properly nowadays, we have to use manual publication addition often even though it shouldn't be. Because DOI cannot be specified immediately, we have to then go back to the item and add the DOI in a separate step. So I suggest adding an option to specify DOI even during manual data entry. This would also be useful for anytime crossref does not work in the future.

**Comment by pekrau** [comment]
Will do. Also, issue #287 is relevant: having the DOI in the entry will then allow attempting update from Crossref when and if it behaves better.
