### ISSUE TITLE
Remove automatic checking of label checkboxes for curators

### ISSUE THREAD

**Issue by akochari** [pekrau/Publications#301]
Currently, when curators add a new item, all checkboxes for labels are automatically checked. I suggest to not do that in case a curator is assigned to more than one label. In this case, the curator most likely needs to make an active choice for which of the labels is appropriate. In our instance, one curator is assigned many labels and ends up having to manually uncheck all irrelevant checkboxes for labels.

**Comment by pekrau** [comment]
Leave pre-checked for curators with few (<=2) labels.
