### ISSUE TITLE
Ideas for improving interface for adding xrefs

### ISSUE THREAD

**Issue by akochari** [pekrau/Publications#312]
There are two things:
- When a new xref is added, the next window that opens is for the publication itself. If one would like to add more xrefs, one needs to again press "Edit xrefs" in the right sidebar. Would be good if the user stayed in the xref editing page after the new one is added.
- Sometimes we make mistakes with xrefs that we added. In those cases, it would be good to be able to edit the existing xrefs. As of now, we have to delete the old one and add a new one.

**Comment by pekrau** [comment]
The first thing: see #329

The second thing: The problem is that an xref entity is identified by its database+accession. There is no other identifier for it. So if either of those is wrong, then delete is the only sensible operation.
