### ISSUE TITLE
Add a variable for open access publication

### ISSUE THREAD

**Issue by akochari** [pekrau/Publications#345]
It would be good to have a variable in the database indicating whether an article has been published open access or not/which license. Then we can display it as a way to incentivise it + it would be easier for those wanting to do some text-mining to know which articles they're allowed to include in their analyses.
I see that crossref gives license information in at least some cases, so perhaps that's good as a start? I did not immediately find anything about licenses in the metadata retrieved from pubmed api.

**Comment by pekrau** [comment]
This is a good idea. I had a quick look at a Crossref JSON file, and found the entry "license" but its contents was not exactly crystal clear. I am not sure that the license refers to the publication, it might refer to the Crossref entry? I will have to investigate further.
